apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.image.repository }}
  name: {{ .Values.image.repository }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: {{ .Values.service.protocol }}
  selector:
    service: {{ .Values.image.repository }}
  type: {{ .Values.service.type }}