apiVersion: v1
kind: Service
metadata:
  labels:
    service: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - name: "4111"
    port: 4111
    targetPort: 3111
    protocol: TCP
  selector:
    service: techtrends
  type: ClusterIP