name: TechTrends - Package with Docker

on:
  push:
    branches:
      - 'main'

jobs:
  Push_to_Docker_Hub:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - name: Set up Python 2.7
#        uses: actions/setup-python@v2
#        with:
#          python-version: '2.7'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          Context: ../../
          file: {context}/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/techtrends:latest


